/**
 * Copyright (c) Crew Dev.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type { HtmlBodyProps } from "./types.ts";
import { VERSION } from "../shared/version.ts";

export function htmlBody({
  css = "",
  html = "",
  head = "",
  client = null,
  hotReloading = null,
}: HtmlBodyProps) {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
${
    hotReloading
      ? `<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/prism.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/normalize-whitespace/prism-normalize-whitespace.min.js"></script>`
      : ""
  }
      ${head}
    <style>
      body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
      } ${css}
    </style>
    ${client ? `<script defer src="${client}"></script>` : ""}
  </head>
  <body>
    ${html}
    ${hotReloading ? hotReloading : ""}
  </body>
</html>`;
}

export const serverTemplate = (
  source: string,
  path: string,
  port = 3000,
) => {
  //TODO(buttercubz) change this en the next release
  return `// generated by snel v${VERSION}
import { htmlBody } from "https://deno.land/x/snel@v${VERSION}/src/server_side/templates.ts";
import { Application } from "https://denopkg.com/crewdevio/tools@main/server_runtime/mod.ts";
import { VERSION } from "https://deno.land/x/snel@v${VERSION}/src/shared/version.ts";
import { join, toFileUrl } from "https://deno.land/std@0.146.0/path/mod.ts";

${source}

await Server({
  path: "${path}",
  port: ${Number(port)},
  dist: true
});
`;
};
